# Generated by Django 5.1.5 on 2025-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wage',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wage',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wage',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wage',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wage',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
