# Generated by Django 5.1.5 on 2025-07-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0002_leavebalance_undefined_1_leavebalance_undefined_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='name',
            new_name='shift_name',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='regular_break',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='short_break',
        ),
        migrations.AddField(
            model_name='shift',
            name='break_min',
            field=models.CharField(choices=[('none', 'No Break'), ('15min', 'Break 15 Minutes'), ('30min', 'Break 30 Minutes')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='staffshift',
            name='cover_shift',
            field=models.BooleanField(default=False),
        ),
    ]
