# Generated by Django 5.1.5 on 2025-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0003_rename_name_shift_shift_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='position_type',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('casual', 'Casual'), ('admin', 'admin')], default='casual', max_length=50),
        ),
    ]
