# Generated by Django 5.1.5 on 2025-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0004_alter_members_position_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wage',
            old_name='start_date',
            new_name='shift_date',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='pay_duration',
        ),
        migrations.RemoveField(
            model_name='wage',
            name='pay_rate',
        ),
        migrations.AddField(
            model_name='members',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=26.55, max_digits=5),
        ),
        migrations.AddField(
            model_name='wage',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wage',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
