# Generated by Django 5.1.5 on 2025-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0005_rename_start_date_wage_shift_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffshift',
            name='has_payslip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wage',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
