# Generated by Django 5.1.5 on 2025-07-28 11:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0007_alter_leaverequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='wage',
            name='tax_withheld',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5),
        ),
    ]
