# Generated by Django 5.1.5 on 2025-08-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0009_alter_members_is_active_timelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
