# Generated by Django 5.1.5 on 2025-08-20 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0010_delete_timelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('branch_number', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StoreMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftapp.stores')),
            ],
            options={
                'unique_together': {('store', 'staff')},
            },
        ),
        migrations.AddField(
            model_name='staffshift',
            name='store_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftapp.storemember'),
        ),
        migrations.AlterUniqueTogether(
            name='staffshift',
            unique_together={('shift_date', 'store_member', 'shift')},
        ),
        migrations.AddField(
            model_name='members',
            name='stores',
            field=models.ManyToManyField(related_name='staffs', through='shiftapp.StoreMember', to='shiftapp.stores'),
        ),
        migrations.AddField(
            model_name='shift',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftapp.stores'),
        ),
        migrations.AddField(
            model_name='members',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiftapp.team'),
        ),
        migrations.RemoveField(
            model_name='staffshift',
            name='staff',
        ),
    ]
