# Generated by Django 5.1.5 on 2025-08-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0011_stores_team_members_role_storemember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemember',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storemember',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storemember',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storemember',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='storemember',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stores',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stores',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stores',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stores',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stores',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='undefined_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='undefined_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='undefined_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='undefined_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='undefined_5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
